### ISSUE TITLE
mac terminal ／ anaconda 安装后启动出现如下问题

### ISSUE THREAD

**Issue by secsafestandard** [Seedarchangel/TuChart#10]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import os,sys,sip,time
ImportError: No module named sip

**Comment by secsafestandard** [comment]
(tuchart) weiMBPde-MacBook-Pro% pip show tuchart
Name: tuchart
Version: 0.1.2.5
Summary: Graphing app for Chinese stocks. 
Home-page: https://github.com/Seedarchangel/TuChart
Author: Rong Zhou Li
Author-email: rzli2@illinois.com
License: MIT
Location: /Users/weimbp/github/stock
-----
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org

**Comment by Seedarchangel** [comment]
你的anaconda版本是多少？

**Comment by Seedarchangel** [comment]
Closed due to non-response.
