### ISSUE TITLE
可以增加设置数据源的配置吗

### ISSUE THREAD

**Issue by royburns** [Seedarchangel/TuChart#14]
我记得tushare有多种数据源，有实时拉取，也有缓存到本地的，sqlite或者mongodb之类的

**Comment by Seedarchangel** [comment]
没有增加是怕变得臃肿。我不记得Tushare自己有sqlite/mongodb配置？
参考http://tushare.org/storing.html，没有看到

**Comment by royburns** [comment]
截图上传失败，nosql就是，往下翻就能看到，

**Comment by royburns** [comment]
不过确实不是tushare直接提供的


MongoDB
pandas目前没有提供直接存入MongoDB的方法，不过依然很简单，而且方式很多，用户可根据自身的业务特点选择存储的结构方式。

使用方法：

import pymongo
import json

conn = pymongo.Connection('127.0.0.1', port=27017)
df = ts.get_tick_data('600848',date='2014-12-22')

conn.db.tickdata.insert(json.loads(df.to_json(orient='records')))

**Comment by royburns** [comment]
用mysql也可以，有个数据存存起来感觉更好点，哈哈哈

**Comment by Seedarchangel** [comment]
@royburns 确实可以考虑一下，目前没加还是因为dependency太复杂会增加使用难度
