### ISSUE TITLE
建议 

### ISSUE THREAD

**Issue by mark-zz** [Seedarchangel/TuChart#22]
对你这个项目有兴趣，我也一直想做行情软件。软件的关键是：
1.市场情绪获得与分析展现，抓取实时的数据，叠加分析，2.股票分类管理，板块，股票，指数等关联分析与叠加分析

最终达到的目标：在什么市场情绪下做什么样的股票。现在的行情软件都不能提供这些信息出来。至于大股东信息，等等那些东西，都不重要。有兴趣可以一起探讨下，我QQ微信: 99945390

**Comment by Seedarchangel** [comment]
你说的是NLP领域的东西。你会THULAC吗？

**Comment by mark-zz** [comment]
根本不需要那么复杂。股票市场很简单，是个情绪市场，情绪是借口驱动的，所以只需要关注到情绪，以及情绪之间的传染范围就够了。所以基本面啊这些，那是巴菲特关心的事。关注技术指标什么之类的，在股市里就一定走偏了.

关联分析不是分析词法，是股市的情绪传染分析，或者涨跌分析，仅此而已
