### ISSUE TITLE
运行main.py 之后网页找不到文件 没有图标显示

### ISSUE THREAD

**Issue by crowluya** [Seedarchangel/TuChart#27]
![image](https://user-images.githubusercontent.com/17447747/47222272-e4d77900-d3e8-11e8-96e7-9d0148acc6a1.png)

**Comment by Seedarchangel** [comment]
请看这个 issue https://github.com/Seedarchangel/TuChart/issues/6
你需要右键一支股票并在右键菜单里选择一个参数，之后这个股票+参数会显示在下面的绘图项里，此时点击开始绘图即可。
