### ISSUE TITLE
error when running: python main.py 

### ISSUE THREAD

**Issue by wuyi1983** [Seedarchangel/TuChart#3]
运行python main.py 出现以下错误

[2380 rows x 3 columns]
Traceback (most recent call last):
  File "main.py", line 312, in <module>
    w = MyUi()
  File "main.py", line 109, in __init__
    retain_size.setRetainSizeWhenHidden(True)
AttributeError: 'QSizePolicy' object has no attribute 'setRetainSizeWhenHidden'

C:\Anaconda2\Lib\site-packages\Tuchart>

这是什么原因？

**Comment by Seedarchangel** [comment]
请问你的Anaconda版本是多少？

**Comment by Seedarchangel** [comment]
已经针对老版anaconda携带的pyqt4做了修复，将在最近一两天推到pypi上。若使用anaconda<4.0.2,绘分笔时gui将出现变形
