### ISSUE TITLE
his webpage is not found  ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by iweey** [Seedarchangel/TuChart#6]
python main.py
Less than 12 hours. Loading previously saved Json...
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
js: /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.

**Comment by Seedarchangel** [comment]
这个error message我也有，影响程序运行吗？

**Comment by iweey** [comment]
影响 ，打开软件后 显示不了K 线

**Comment by Seedarchangel** [comment]
你是在anaconda/lib/python2.7/site-packages/tuchart的文件夹里跑`python main.py`吗？
如果在anaconda/lib/python2.7/site-packages里跑`python tuchart`,会有这个问题。

**Comment by Seedarchangel** [comment]
你的chrome版本是多少？我目前没办法重现这个问题。有一个方案是在你运行tuchart的directory下新建一个空白的render.html，如果问题还在请留言。

**Comment by wangchaoduo** [comment]
你好我遇到了相同的问题，在新建了render.html后不再报warning但是右侧图表的界面一直都是空白，安装方法和readme里写的一样

**Comment by Seedarchangel** [comment]
@wangchaoduo 
这个问题很迷，你的系统默认浏览器是哪个？

**Comment by jamesding** [comment]
我也是这个问题，新建了render.html后不再报warning但是右侧图表的界面一直都是空白。绘图项那没数据？

**Comment by Seedarchangel** [comment]
@jamesding 可以说一下把你选择绘图后render.html里的内容截个图吗？

**Comment by Seedarchangel** [comment]
我...终于知道为什么会有这个问题了...原因非常蠢...我的doc没写清楚使用方法
光选中股票是不会绘图的。如果想绘制一支股票的参数，要右键这支股票，从弹出的菜单里选一个参数，此时这个参数会出现在下面的方框里，点击开始绘图才会真正绘图....

**Comment by wangchaoduo** [comment]
🤔🤔🤔🤔哈哈哈哈哈迷了迷了
